version: '3'

services:

    dcf_service:
        container_name: dcf_service
        image: tomcat
        ports:
            - "8080:8080"
        volumes:
            - ./target:/usr/local/tomcat/webapps
        environment:
            DCF_SERVICE_ENVIRONMENT: "prod"
