version: '3'

services:

    dcfsmysqldb:
      container_name: dcfsmysqldb
      image: mysql:5.6.42
      environment:
        MYSQL_ROOT_PASSWORD: "nimble"
      volumes:
        - ./db:/docker-entrypoint-initdb.d

    dcfsksql:
        container_name: dcfsksql
        image: confluentinc/cp-ksql-server:4.1.2
        volumes:
          - ./ksql:/etc/ksql/
        command: bash -c "sed \"s/dcfs_kafka_ssl_password/${dcfs_kafka_ssl_password}/g\" /etc/ksql/ksql-server.properties.template > /etc/ksql/ksql-server.properties && /usr/bin/ksql-server-start /etc/ksql/ksql-server.properties"
        environment:
            dcfs_kafka_ssl_password: $dcfs_kafka_ssl_password

    dcfstomcat:
        container_name: dcfstomcat
        image: tomcat
        environment:
            dcfs_kafka_ssl_login: $dcfs_kafka_ssl_login
            dcfs_kafka_ssl_password: $dcfs_kafka_ssl_password
        ports:
            - "28080:8080"
        volumes:
            - ./target:/usr/local/tomcat/webapps
        depends_on:
          - dcfsmysqldb
          - dcfsksql
          
