apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  app: dcf_service
  name: dcf_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcf_service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: dcf_service
    spec:
      containers:
      - image: nimbleplatform/dcf_service:IMAGE_TAG
        imagePullPolicy: Always
        name: dcf_service
        env:
        - name: ENVIRONMENT
          value: "prod"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
