apiVersion: v1
kind: Service
metadata:
  labels:
    app: dcf_service
  name: dcf_service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dcf_service